apiVersion: v1
kind: Service
metadata:
  name: autonomous-integration-platform
  labels:
    app: autonomous-integration-platform
spec:
  type: ClusterIP
  selector:
    app: autonomous-integration-platform
  ports:
    - name: http
      port: 80
      targetPort: 8000
